version: '3.8'
services:
  nginx:
    image: "nginx"
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx-selfsigned.crt:/etc/ssl/private/nginx-selfsigned.crt"
      - "./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key"
  database-devbox:
    # :13.2, pinned on 2022-05-31
    image: "healthsamurai/aidboxdb@sha256:df7e461f6010eb9746c9361b7a3b83bea9217ac8fe6597cb88026a5f4f83ad8e"
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER:     "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "postgres"

  devbox:
    # :latest, pinned on 2022-08-27
    image: "healthsamurai/devbox@sha256:a010d77ce2fa31222ae334fabc529734d6fbf5aa09be8bc2c2f88f2fe8aa707b"
    ports:
      - "8888:8888"
    environment:
      PGHOST: "database-devbox"
      AIDBOX_LICENSE: "${AIDBOX_LICENSE:?err}"
      AIDBOX_CLIENT_ID: "root"
      AIDBOX_CLIENT_SECRET: "secret"
      AIDBOX_ADMIN_ID: "admin"
      AIDBOX_ADMIN_PASSWORD: "secret"
      AIDBOX_PORT: "8888"
      AIDBOX_FHIR_VERSION: "4.0.0"
      PGPORT: "5432"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
      PGDATABASE: "postgres"
